version: 2.1
jobs:
  build-test:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run npm audit to check for vulnerabilities
      - run:
          name: Run npm audit
          command: npm audit

      # Fix vulnerabilities if any
      - run:
          name: Fix vulnerabilities
          command: npm audit fix || echo "Manual intervention required for some issues"

      # Run tests
      - run: npm run test

      # Run build
      - run: npm run build

workflows:
  node-tests:
    jobs:
      - build-test
